"""add_reviews_and_ratings

Revision ID: a004
Revises: a003
Create Date: 2025-12-17 14:17:18.644186

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a004'
down_revision = 'a003'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clinic_reviews',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('clinic_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('ambiance_rating', sa.Integer(), nullable=True),
    sa.Column('staff_rating', sa.Integer(), nullable=True),
    sa.Column('hygiene_rating', sa.Integer(), nullable=True),
    sa.Column('review_title', sa.String(length=200), nullable=True),
    sa.Column('review_text', sa.Text(), nullable=True),
    sa.Column('is_verified', sa.Boolean(), nullable=True),
    sa.Column('is_approved', sa.Boolean(), nullable=True),
    sa.Column('moderation_notes', sa.Text(), nullable=True),
    sa.Column('helpful_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['clinic_id'], ['clinics.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clinic_reviews_id'), 'clinic_reviews', ['id'], unique=False)
    op.create_table('review_helpful_votes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('is_helpful', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['doctor_reviews.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_review_helpful_votes_id'), 'review_helpful_votes', ['id'], unique=False)
    op.add_column('doctors', sa.Column('average_rating', sa.Float(), nullable=True))
    op.add_column('doctors', sa.Column('total_reviews', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('doctors', 'total_reviews')
    op.drop_column('doctors', 'average_rating')
    op.drop_index(op.f('ix_review_helpful_votes_id'), table_name='review_helpful_votes')
    op.drop_table('review_helpful_votes')
    op.drop_index(op.f('ix_clinic_reviews_id'), table_name='clinic_reviews')
    op.drop_table('clinic_reviews')
    # ### end Alembic commands ###